= yourCMDB Admin Guide
Michael Batz <michael@yourcmdb.org>
:toc: left
:icons: font
:source-highlighter: pygments

== Getting started

=== The concept of yourCMDB





=== Setup
yourCMDB is designed for working in a LAMP/WAMP environment. The following software needs to be installed before installing yourCMDB:

* a webserver with PHP support (e.g. Apache)
* PHP >= 5.3 with the follwing libraries:
** GD
** MySQL
** LDAP
** CLI
* MySQL database server

If all the required software is installed, download the current version of yourCMDB and extract the files in a directory of your choice, for example in /opt/yourCMDB. After that, link the web subdirectory in your webserver's document root.

Please see the following example:
[source,bash]
----
cd /opt
tar -xzvf yourcmdb.tar.gz
ln -s /opt/yourCMDB/web /var/www/html/yourCMDB #<1>
----
<1> if the document root is /var/www/html

The data of the yourCMDB installation will be stored in a MySQL database. So create a database and a database user on your MySQL server for yourCMDB.

Please see the following example:
[source,sql]
----
CREATE DATABASE yourcmdb;
GRANT ALL ON yourcmdb.* TO yourcmdb@localhost IDENTIFIED BY 'secret1234';
----

In the yourCMDB etc directory, you will find the configuration file datastore-configuration.xml, which stores the parameters that are used for the database connection. Edit this file and put in the correct parameters:
[source,xml]
.datastore-configuration.xml
----
<datastore-config>
	<datastore>
		<parameter key="driver" value="pdo_mysql" />
		<parameter key="host" value="localhost" />
		<parameter key="port" value="3306" />
		<parameter key="db" value="yourcmdb" />
		<parameter key="user" value="yourcmdb" />
		<parameter key="password" value="secret1234" />
	</datastore>
</datastore-config>
----

Now you can let the yourCMDB setup script creating the database structure and default users:

[source,bash]
----
/opt/yourCMDB/scripts/setup.php
----

It will connect to the configured database and create the required tables.

To get authentication and authorisation working, please setup the base URL for yourCMDB in the configuration file view-configuration.xml. Change the following line to fit your needs:

[source,xml]
----
<url base="http://127.0.0.1" />
----

For example, if your yourCMDB setup is available under https://www.example.com, use the following configuration:
[source,xml]
----
<url base="https://www.example.com" />
----

yourCMDB is now installed and you can login with the follwing credentials:
[listing]
username: admin
password: yourcmdb






=== Update an existing version
To upgrade an exisiting version, please at first create a backup of your existing installtion. A backup should include the following parts:

* configuration files (yourCMDB/etc directory
* database dump

==== install the new version
Now, rename the exisitng current yourCMDB directory, download the current version and extract the files to a directory of your choice. After that, link the web subdirectory in your webserver's document root.

Example:
[source,bash]
----
cd /opt
mv /opt/yourCMDB /opt/yourCMDB_old
tar -xzvf yourcmdb.tar.gz
ln -s /opt/yourCMDB/web /var/www/html/yourCMDB #<1>
----
<1> if the document root of your webserver is /var/www/html

==== migrate configuration files
Between the versions, the configuration files can change or some new files were added. Use the etc directory of the new yourCMDB version and migrate your configuration changes from the old version.


==== migrate database structure
Between the versions, the database structure can change. If you upgrade from versions >= 0.8, the yourCMDB setup tool will upgrade your database structure for you. Please run:

[listing]
/opt/yourCMDB/scripts/setup.php

If you want to upgrade from a version < 0.8, please first do an update to version 0.8 and use the update-<version>.sql files in the <yourcmdb>/sql directory (you'll find them in versions <= 0.8). For each version, where the database schema was changed, you'll find a file. For example, if you update from version 0.4 to 0.5, use the update-0.5.sql file. If you update from version 0.3 to 0.5 use the update-0.4.sql file and after that, the update-0.5.sql file. 






== Object Type configuration
Object types were configured in XML configuration files. The start file is objecttype-configuration.xmlm where multiple files can be included.

=== The structure of objecttype-configuration.xml
Let's start with a simple example of the object type configuration to understand the structure of the file: 

[source,xml]
----
<object-types>
      <group name="network devices">
            <object-type name="router">
               [...]
            </object-type>
            <object-type name="switch">
               [...]
            </object-type>
      </group>
      <group name="locations">
         [...]
      </group>
</object-types>
----

The configuration of object types starts with an <object-types>-tag. Object types are organized in groups (<group>-tags) with an unique name. The groups are used for grouping the object types in the WebUI and REST API. Object types are defined within a group using the <object-type> tag. Each object type must have a name, that is unqiue for the whole configuration (so it is not possible to define two object types with the same name in different groups). For the name of object types, the following restrictions are set: 

* max length: 64 characters
* not allowed characters are dots "." or spaces " " or slashes "/"

=== define an object type
Below, you see an example of the definition of an object type:

[source,xml,options="nowrap"]
----
<object-type name="router">
      <static>
              <comment>A comment on router objects...</comment>
      </static>
      <links>
              <link name="Search for manufacturer" href="http://www.google.de/#q=%manufacturer%" />
      </links>
      <eventdefs>
                      <eventdef name="exportObjects" label="Export Objects" />
      </eventdefs>
      <fields>
              <fieldgroup name="network">
                      <field name="hostname" type="text" label="Hostname" summaryfield="true" labelfield="true" />
                      <field name="management-ip" type="text" label="management IP" summaryfield="true"/>
                      <field name="snmpCommunity" type="text" label="SNMP community" default="public"/>
                      <field name="snmpVersion" type="text" label="SNMP version" default="v2c" />
                      <field name="snmpPort" type="text" label="SNMP port" default="161" />
              </fieldgroup>
              <fieldgroup name="hardware">
                      <field name="manufacturer" type="text" summaryfield="true"/>
                      <field name="serialno" type="text" label="serial number" />
                      <field name="maintenance-contract" type="text" label="maintenance contract" />
              </fieldgroup>
              <fieldgroup name="age">
                      <field name="setup-date" type="date" label="setup date" />
                      <field name="contract-date" type="date" label="service contract date" />
              </fieldgroup>
              <fieldgroup name="location">
                      <field name="location" type="objectref-datacenter" label="location" />
              </fieldgroup>
              <fieldgroup name="admin">
                      <field name="Name" type="text" />
                      <field name="Mail" type="text" />
              </fieldgroup>
              <fieldgroup name="Management">
                      <field name="monitoring" label="Monitoring with OpenNMS" type="boolean" />
                      <field name="config-backup" label="Backup of configuration" type="boolean" />
              </fieldgroup>
              <fieldgroup name="Comment">
                      <field name="comment" type="textarea" />
              </fieldgroup>
      </fields>
 </object-type>
----

=== fields
The most important thing of an object type is the definition of fields within the <fields>-tag. The fields of an object type are organized in groups (<fieldgroup>-tag). Each field is defined using the <field>-tag and must have a unique name for the whole object type (so it is not allowed to use the same field name in two groups of a single object type). The following limitations are given for the fieldname:

* max length: 64 characters
* not allowed characters are dots "." or spaces " " or slashes "/"
* the following strings are not allowed: action, id, type, yourCMDB_* (all strings starting with "yourCMDB_")

Each field has a data type that is defined in the type attribute and controls the behavior of the field in the web ui. You can use the following data types: 

|===
|type |description |behavior

|text
|text field
|simply shows/stores the text

|textarea
|textarea with multiple lines for bigger texts
|simply shows/stores the text

|boolean
|shows a checkbox
|stores only one of the value true/false

|date
|shows a datepicker
|stores the date

|objectref-<objecttype>	
|shows a selection of all objects of type <objecttype>	
|stores the reference to an object of type <objecttype>

|password
|password field	
|Shows a password generator in edit mode. Hides passwords by default. 
|===

Optionally you can define a label using the label attribute for the field that is shown in the WebUI instead of the field name, which is limited in some points.

If you want to define a default value for the field, just use the attribute default. A default value is shown in the forms of the WebUI, when adding a new object.

The next attribute is summaryfield, which can be true or false and is false by default. Summary fields are the fields that summarize an object and are shown in lists or search results in the WebUI.

The last attribute is labelfield, which can be true or false and is false by default. Label fields are used for defining the content of an object label. See Label Printing for more information. 


=== links
You can define external links to other websites for the objects of a specific type. In the links you can use the content of object fields. For example:

[source,xml]
----
<links>
      <link name="Search for manufacturer" href="http://www.google.de/#q=%manufacturer%" />
</links>
----

All links are defined between the <links>-tags. A link needs a name and a target, which is defined with the href attribute. Within the target you can use %<fieldname>% as a variable. So in the example above, %manufacturer% is replaced with the content of the field “manufacturer” of the particular object. You can also use the following variables:

* %yourCMDB_object_id%
* %yourCMDB_object_type%


=== eventDefs
You can define custom events to use with the yourCMDB TaskScheduler.


=== static information
You can add some static informations to all objects of a specific type using the <static>-tags. At the moment there only is an implementation for the information in the <comment> section, where you can add comments to all object of a specific type. You can also use the following variables in comments:

* %fieldname%
* %yourCMDB_object_id%
* %yourCMDB_object_type%


=== use subfiles
In the main configuration file, you can use <includeconfig>-tags to store parts of the configuration in seperate files. That makes it more easy to handle big setups with many object types and groups. In the yourCMDB default configuration these files are stores in the objecttypes subdirectory: 

[source,xml]
----
<object-types>
      <includeconfig file="objecttypes/locations.xml" />
      <includeconfig file="objecttypes/network-devices.xml" />
</object-types>
----






== ExportAPI

== Authentication

