ALTER TABLE CmdbObject MODIFY active ENUM('A', 'D', 'N');
ALTER TABLE CmdbObject CONVERT TO CHARACTER SET utf8;
ALTER TABLE CmdbObjectField CONVERT TO CHARACTER SET utf8;
ALTER TABLE CmdbObjectLink CONVERT TO CHARACTER SET utf8;
ALTER TABLE CmdbObjectLog CONVERT TO CHARACTER SET utf8;
